version: '2'
services:
  loadb:
    build: lbal
    ports:
     - "80:80"
    depends_on:
      - "web1"
      - "web2"
  web1:
    build: webapp
#    ports:
      #- "5000:5000"
    depends_on:
      - "redis"
  web2:
    build: webapp
#    ports:
#     - "5000:5000"
    depends_on:
      - "redis"
  redis:
    image: "redis:alpine"
